### ISSUE TITLE
How to make tab-width 4 space

### ISSUE THREAD

**Issue by avatar-lavventura** [EricCrosson/pine-script-mode#16]
Here tabs make 3 space indent, which gives an error. How can I force pine-script-mode to do indention as 4 space?

```
if is_div_long
   label.new()
```

**Comment by darrylhebbes** [comment]
Hi, yes this is a feature I wish to add to this mode. I will get back to you with a temporary solution while we add indenting and syntax formatting ( based on common guidelines) to this mode.

**Comment by avatar-lavventura** [comment]
I have tried something as follows but it did not work :(

```
(add-hook 'pine-script-mode
  (lambda ()
    (setq tab-width 4)
    (untabify (point-min) (point-max))))
```

**Comment by darrylhebbes** [comment]
Hi, try this (untested)

```
(defun my-custom-settings-fn ()
  (setq indent-tabs-mode nil)   ;; nil for spaces
  (setq tab-stop-list (number-sequence 2 200 2))
  (setq tab-width 4)
  (setq indent-line-function 'insert-tab))

(add-hook 'pine-script-mode-hook 'my-custom-settings-fn)
```

**Comment by darrylhebbes** [comment]
But I am not sure we need to implement the hook in the `pine-script-mode`. I am fairly new to custom modes.
I will investigate

**Comment by avatar-lavventura** [comment]
> Hi, try this (untested)
> 
> ```
> (defun my-custom-settings-fn ()
>   (setq indent-tabs-mode nil)   ;; nil for spaces
>   (setq tab-stop-list (number-sequence 2 200 2))
>   (setq tab-width 4)
>   (setq indent-line-function 'insert-tab))
> 
> (add-hook 'pine-script-mode-hook 'my-custom-settings-fn)
> ```

Thanks, this works by the way.

**Comment by darrylhebbes** [comment]
Ok great, I will however still build it into the mode by default.
